"""Add is_admin to User

Revision ID: 632b3d76dd1f
Revises: 569d41d67b28
Create Date: 2025-06-28 15:26:38.818486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632b3d76dd1f'
down_revision = '569d41d67b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_image', sa.String(length=120), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('background_image')

    # ### end Alembic commands ###
