"""Add torrent_file to Game

Revision ID: 7c89ced54304
Revises: 632b3d76dd1f
Create Date: 2025-07-01 21:45:55.218424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c89ced54304'
down_revision = '632b3d76dd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('torrent_file', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('torrent_file')

    # ### end Alembic commands ###
